# Generated by Django 2.1.5 on 2020-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('publication_date', models.DateTimeField(verbose_name='date published')),
                ('story_text', models.CharField(max_length=200)),
            ],
        ),
    ]
